# Generated by Django 4.0.3 on 2022-03-28 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('is_finished_before_deadline', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('F', 'Finished'), ('D', 'Doing'), ('U', 'Undone')], max_length=1)),
                ('todo_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todos.todotype')),
            ],
        ),
    ]
