# Generated by Django 4.0.3 on 2022-03-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
