# Generated by Django 4.0.3 on 2022-04-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_todotype_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotype',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
    ]
