# Generated by Django 4.0.3 on 2022-03-30 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_alter_subtodo_todo_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='todo_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todos.todotype'),
        ),
    ]
