# Generated by Django 4.0.3 on 2022-04-03 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_todoitem_todo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtodo',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_todos', to='todos.todo'),
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
